version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ecommerce-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    volumes:
      - ecommerce-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  ecommerce-store:
    image: node:14
    container_name: ecommerce-store
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mysecretpassword@ecommerce-db:5432/mydatabase
    command: sh -c "npm install && npm run dev"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  ecommerce-vol:
